name: Node.js CI/CD with Docker

on:
 push:
   branches:
     - main

jobs:
 build:
   runs-on: self-hosted



   steps:
     - name: Checkout Code
       uses: actions/checkout@v4



     - name: Build Docker Image
       run: |
         cd /home/strapi/actions-runner-strapi/strapi/cht-strapi/cht-strapi
         sudo -u jazzam docker build -t jazzam-frontend-image:latest .


     - name: Stop & Remove Existing Container
       run: |
         CONTAINER_ID=$(sudo -u strapi docker ps -aq --filter "name=jazzam-frontend-container")
         if [ ! -z "$CONTAINER_ID" ]; then
           sudo -u jazzam docker stop jazzam-frontend-container
           sudo -u jazzam docker rm jazzam-frontend-container
         fi


     - name: Run New Container
       run: |
         sudo -u strapi docker run -d -p 3000:3000 --name jazzam-frontend-container jazzam-frontend-image:latest


     - name: Prune Unused Images & Containers
       run: |
         sudo -u jazzam docker system prune -af


 nginx:
   runs-on: self-hosted
   needs: build
   steps:
     - name: Nginx Configuration
       run: |
         sudo nginx -t
         sudo systemctl restart nginx

